#!/bin/bash

# Script to pre-process the insert fasta file generated by Savana and divide it into multiple fasta files per SV ID
INPUT_INSERTS=$1
OUTPUT=$2
mkdir -p ${OUTPUT}

source activate seqkit_env
# Get the sequences to align from the savana output (ID[0-9]+-INS.+)
grep '^>' ${INPUT_INSERTS} | cut -d '-' -f 1 | sort -u | sed 's/^>//g' > ${OUTPUT}/ins_ids.txt

# Use seqkit to split the fasta by insertion ID
while read INS_ID; do
    seqkit grep -r -p "${INS_ID}-" ${INPUT_INSERTS} > ${OUTPUT}/${INS_ID}.fasta
done < ${OUTPUT}/ins_ids.txt

conda deactivate